// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imlruptdgkyitqwyijtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbHJ1cHRkZ2t5aXRxd3lpanR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MzQ1MjQsImV4cCI6MjA1MzIxMDUyNH0.M0uNx_IT_6eejKrNHJhQ1j9mNwR7DGeSKq9cxSOnJp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);